#!/bin/sh
# Regenerate THIRD_PARTY_NOTICES.md from the modules linked into release binaries.

set -eu

ROOT=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)
WORK=$(mktemp -d 2>/dev/null || mktemp -d -t lw-notices)
trap 'rm -rf "$WORK"' EXIT HUP INT TERM

MODULES="$WORK/modules"
OUTPUT="$WORK/THIRD_PARTY_NOTICES.md"
: >"$MODULES"

for target in darwin/amd64 darwin/arm64 linux/amd64 linux/arm64; do
	os=${target%/*}
	arch=${target#*/}
	(
		cd "$ROOT"
		CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go list -deps \
			-f '{{with .Module}}{{if not .Main}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}{{end}}' \
			./cmd/lw
	) >>"$MODULES"
done

LC_ALL=C sort -u "$MODULES" -o "$MODULES"

find_license() {
	dir=$1
	for name in LICENSE LICENSE.txt LICENSE.md COPYING COPYING.txt; do
		if [ -f "$dir/$name" ]; then
			printf '%s\n' "$dir/$name"
			return 0
		fi
	done
	return 1
}

GO_LICENSE="$(go env GOROOT)/LICENSE"
if [ ! -f "$GO_LICENSE" ] && [ -f "$(go env GOROOT)/../LICENSE" ]; then
	# Homebrew keeps the distribution license beside its libexec GOROOT.
	GO_LICENSE="$(go env GOROOT)/../LICENSE"
fi
[ -f "$GO_LICENSE" ] || {
	printf 'error: Go toolchain license not found\n' >&2
	exit 1
}

{
	cat <<'EOF'
# Third-party notices

This file records licenses for code linked into the prebuilt `lw` binaries.
It is generated by `scripts/generate-third-party-notices.sh`; do not edit it by hand.

## Go standard library

Source: <https://go.dev/>

```text
EOF
	cat "$GO_LICENSE"
	cat <<'EOF'
```
EOF

	while IFS='|' read -r module version dir; do
		[ -n "$module" ] || continue
		license=$(find_license "$dir") || {
			printf 'error: no license file found for %s@%s\n' "$module" "$version" >&2
			exit 1
		}
		printf '\n## %s %s\n\n' "$module" "$version"
		printf 'Source: <%s>\n\n' "https://$module"
		printf '%s\n' '```text'
		cat "$license"
		printf '%s\n' '```'
	done <"$MODULES"
} >"$OUTPUT"

mv "$OUTPUT" "$ROOT/THIRD_PARTY_NOTICES.md"
